apiVersion: v1
kind: Service
metadata:
  name: gymaudit-web-service
  namespace: gymaudit
spec:
  selector:
    app: gymaudit-web
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80